project_id = "vault-chat"
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 100
[db]
port = 54322
shadow_port = 54320
major_version = 17
[db.seed]
enabled = false
[realtime]
enabled = true
[studio]
enabled = true
port = 54323
[auth]
enabled = true
site_url = "https://chat.localhost:8443"
additional_redirect_urls = []
enable_signup = false
[auth.email]
enable_signup = false
[storage]
enabled = true
